main: me.michqql.bhd.BetterHitDetectionPlugin
name: BetterHitDetection
version: 0.4.2

api-version: 1.16

softdepend:
  - InventoryLib

commands:
  betterhitdetection:
    aliases: ['bhd']
  kb:
    aliases: ['knockback']
  preset:
    aliases: ['profile']
  damageCalculator:
    aliases: ['damage','dc']